### ISSUE TITLE
access to data? property in rpcError

### ISSUE THREAD

**Issue by andersbc** [shekohex/jsonrpc-ts#24]
How do you access the optional `data` property of an RpcError?

`RpcError` is defined [here](https://github.com/shekohex/jsonrpc-ts/blob/28d107eadfd832138f4de9ff9117b9f97b016f87/src/rpc-error.ts#L4):

```ts
export class RpcError<TError = any> extends Error {
  constructor(private readonly err: RpcResponseError<TError>) {
      super();
      super.message = err.message;
  }

  public getCode(): RpcErrorCode | number {
      return this.err.code;
  }
}
```
I can get the `code` and `message`, but the `data?` property - which is part of the [`RpcResponseError`](https://github.com/shekohex/jsonrpc-ts/blob/28d107eadfd832138f4de9ff9117b9f97b016f87/src/interfaces/rpc-response-error.interface.ts#L7) - is not exposed. Or am I missing something?

**Comment by shekohex** [comment]
Yes, it is missing, could you create a PR for that? I would review and make a new release for it

**Comment by andersbc** [comment]
all right, I'll give it a shot and then you can take a look at it :-) I'm not to experienced a programmer, but I guess it's a minor change.

**Comment by shekohex** [comment]
closed in #25

**Comment by shekohex** [comment]
added in `v0.2.1` 🎉

**Comment by andersbc** [comment]
Thank you :-)
